### ISSUE TITLE
Error on **/*

### ISSUE THREAD

**Issue by germtb** [jonschlinkert/contains-path#1]
contains is crashing when trying the pattern `**/*/whatever`. I can see why it shouldn't work, but I don't think it should raise an exception.

**Comment by jonschlinkert** [comment]
hmm, it throws? yeah that doesn't sound right. Could you paste the entire code snippet you used, so I can recreate? thanks for reporting

**Comment by germtb** [comment]
contains('/a/b/c', '**/a')

```
SyntaxError: Invalid regular expression: /(^|\/)**\/a($|\/)/: Nothing to repeat
```

However, one `*` does not throw anything.

**Comment by jonschlinkert** [comment]
Oh ok, I didn't have time to look at the code earlier, thanks for the additional detail. Marking as a bug since those are actually valid path characters. however, it's important to know that this doesn't take glob patterns, it only checks to see if a filepath or path segment is contained within another given path. 

to fix the bug we just need to escape special characters in the path that is converted to regex.
Want to do a pr? Or I can push up a fix as soon as I have a chance. thanks again

**Comment by germtb** [comment]
Yeah, I assumed this package would not deal with glob, it's just I am using the same patterns for both glob and contains-path, and I guessed the exception shouldn't be thrown. I will create a PR with the info I found at http://stackoverflow.com/questions/3115150/how-to-escape-regular-expression-special-characters-using-javascript

Edit:

PR: https://github.com/jonschlinkert/contains-path/pull/2

**Comment by germtb** [comment]
https://github.com/jonschlinkert/contains-path/pull/2
